project_name: flipbit
builds:
- env:
  - CGO_ENABLED=0
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
  - name: bitflip
    github:
      owner: aybabtme
      name: homebrew-tap
    commit_author:
      name: goreleaserbot
      email: antoinegrondin@gmail.com

nfpms:
  - package_name: bitflip
    formats:
      - deb
